---
apiVersion: v1
kind: Service
metadata:
  name: vaccine-issuer-agent
  namespace: vaccine-issuer
spec:
  type: ClusterIP         # Default type (ClusterIP), NodePort, LoadBalancer
  selector:
    app: vaccine-issuer-agent
  ports:
    - name: admin-port
      port: 8001          #service port http
      targetPort: 8001
      protocol: TCP
    - name: http-port
      port: 8000          #service port http
      targetPort: 8000 
      protocol: TCP


# kubectl port-forward service/vaccine-issuer-agent 8180:8180 -n vaccine-issuer
# kubectl port-forward deployment.apps/vaccine-issuer-agent 8180:8180 -n vaccine-issuer

# localhost:8180/ 

