---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaccine-issuer-agent
  namespace: vaccine-issuer
  labels:
    app: vaccine-issuer-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaccine-issuer-agent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: vaccine-issuer-agent
    spec:
      containers:
        - name: vaccine-issuer-agent
          image: bcgovimages/aries-cloudagent:py36-1.16-1_0.8.1
          imagePullPolicy: Always
          ports:
            - name: agnt-admin-port
              containerPort: 8001
              protocol: TCP
            - name: agnt-http-port
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: vaccine-issuer-agent-configmap
          env:
            - name: ACAPY_WALLET_KEY
              valueFrom:
                secretKeyRef:
                  name: vaccineissuersecret
                  key: acapywalletkey
            - name: ACAPY_WALLET_STORAGE_CREDS
              valueFrom:
                secretKeyRef:
                  name: vaccineissuersecret
                  key: acapywalletstoragecred
          command: [
              "/bin/bash",
              "-c",
              "aca-py start \
              --admin '0.0.0.0' 8001 \
              --inbound-transport http '0.0.0.0' 8000 \
              --outbound-transport http \
              --connections-invite",
            ]
