---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaccine-issuer-configmap
  namespace: vaccine-issuer
data:
  # acapy variables
  ACAPY_URL: "http://vaccine-issuer-agent.vaccine-issuer.svc.cluster.local:8001" # socket - ?
  SCHEMA_ID: "EosRZ6aKyEgWVQqQyza8w:2:Vaccine_Credential:1.2"
  SCHEMA_NAME: "Vaccine_Credential"
  SCHEMA_VERSION: "1.2"
  CRED_DEF_ID: "EosRZ6aKyEgWVQqQyza8w:3:CL:42474:Vaccine Credential 1.2"
  PUBLIC_DID: "EosRZ6aKyEgWVQqQyza8w"
  # ACAPY_ADMIN_API_KEY: secret
  # client variables
  # CLIENT_URL: "http://vaccine-issuer-agent.vaccine-issuer.svc.cluster.local:3000" # socket
  # server variables
  SERVER_ADDRESS: 0.0.0.0:8180
