---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vaccine-issuer-configmap
  namespace: vaccine-issuer
data:
  # acapy variables
  ACAPY_URL: "http://vaccine-issuer-agent.vaccine-issuer.svc.cluster.local:8001" # socket - ?
  # ACAPY_ADMIN_API_KEY: secret
  # client variables
  # CLIENT_URL: "http://vaccine-issuer-agent.vaccine-issuer.svc.cluster.local:3000" # socket
  # server variables
  SERVER_ADDRESS: 0.0.0.0:8180
  SCHEMA_ID: "CiW8u785VTBW1S9AsPXGXi:2:Vaccine_Credential:3.0"
  SCHEMA_NAME: "Vaccine_Credential"
  SCHEMA_VERSION: "3.0"
  CRED_DEF_ID: "CiW8u785VTBW1S9AsPXGXi:3:CL:51753:IAMZA Vaccine Credential"
  PUBLIC_DID: "CiW8u785VTBW1S9AsPXGXi"
